# Generated by Django 3.2.5 on 2022-01-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品画像'),
        ),
    ]
